Maestro is a tool for orchestrating co-simulation of FMUs. It features both a command line interface and a web interface.
The web interface is used internally by the INTO-CPS Desktop Application, but it can also be downloaded and used seperately.

| All development efforts related to Maestro is available at https://github.com/INTO-CPS-Association/maestro.
| Maestro1 Documentation is available here: https://into-cps-maestro.readthedocs.io/en/docs/
| Maestro2 is currently under development and available at the branch 2.0.0-alpha with documentation here: https://into-cps-maestro.readthedocs.io/en/latest/.
